### ISSUE TITLE
Handle resource with Fn::Sub intrinsic function

### ISSUE THREAD

**Issue by confix** [confix/cfn-appsync-include#1]
We have to handle templates where mapping templates require substitution of variables using the `Fn::Sub` intrinsic function.

This functionality might be useful for request mapping templates of dynamodb TransactWriteItems operation or HTTP resolvers invoking step functions.

```yaml
Resources:
  MyResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref Api
      TypeName: Query
      FieldName: user
      RequestMappingTemplate:
        Fn::Sub:
          - !File MyTemplate.request.vtl
          - TableName: !Ref MyTable 
```
